// Command cmdmetagen generates command_info_snapshot.go, the shipped snapshot
// of COMMAND metadata records, fetched through the client's own COMMAND parser
// (run against the pinned client-libs-test image so module metadata is
// included):
//
//	go run ./internal/cmdmetagen -addr localhost:6379 -out command_info_snapshot.go
//
// The output is checked in: a regeneration is a reviewable diff, gated by the
// root eligibility tests. The snapshot carries every application-facing
// command record so consumers beyond CSC eligibility (e.g. routing) can share
// it. When regenerating against a new release, verify newly cacheable
// commands with a tracking probe first (see cscMetadataCorrections in
// csc_commands.go for known gaps).
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"

	redis "github.com/redis/go-redis/v9"
)

func main() {
	addr := flag.String("addr", "localhost:6379", "address of the Redis server to read COMMAND metadata from")
	out := flag.String("out", "command_info_snapshot.go", "output file")
	flag.Parse()

	ctx := context.Background()
	client := redis.NewClient(&redis.Options{Addr: *addr, Protocol: 3})
	defer client.Close()

	infos, err := client.Command(ctx).Result()
	if err != nil {
		fatalf("COMMAND failed: %v", err)
	}

	names := make([]string, 0, len(infos))
	for name := range infos {
		lower := strings.ToLower(name)
		// Internal module aliases; their application-facing forms are the
		// ft./ts. records.
		if strings.HasPrefix(lower, "_") ||
			strings.HasPrefix(lower, "search.") ||
			strings.HasPrefix(lower, "timeseries.") {
			continue
		}
		names = append(names, name)
	}
	sort.Slice(names, func(i, j int) bool {
		return strings.ToLower(names[i]) < strings.ToLower(names[j])
	})

	source := describeServer(ctx, client)
	// Pre-8.10 servers lack script_runner and module dont_cache tips: a
	// snapshot from one would silently miss its negative signals.
	m := regexp.MustCompile(`redis_version (\d+)\.(\d+)`).FindStringSubmatch(source)
	if m == nil {
		fatalf("cannot determine the server version (%q); refusing to generate", source)
	}
	major, _ := strconv.Atoi(m[1])
	minor, _ := strconv.Atoi(m[2])
	if major < 8 || (major == 8 && minor < 10) {
		fatalf("server is redis %s.%s; the snapshot must be generated from >= 8.10", m[1], m[2])
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by internal/cmdmetagen; DO NOT EDIT.
//
// Source: %s
//
// Shipped snapshot of COMMAND metadata records: the static layer of
// command-metadata resolution (see command_metadata.go).

package redis

var commandInfoSnapshot = map[string]*CommandInfo{
`, source)
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: {%s},\n", strings.ToLower(name), record(infos[name]))
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fatalf("gofmt of generated source failed: %v\n%s", err, b.Bytes())
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatalf("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d command records (of %d total)\n",
		*out, len(names), len(infos))
}

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "cmdmetagen: "+format+"\n", args...)
	os.Exit(1)
}

// record renders one CommandInfo literal, omitting zero fields.
func record(info *redis.CommandInfo) string {
	fields := []string{fmt.Sprintf("Name: %q", strings.ToLower(info.Name))}
	if info.Arity != 0 {
		fields = append(fields, fmt.Sprintf("Arity: %d", info.Arity))
	}
	if len(info.Flags) > 0 {
		fields = append(fields, "Flags: "+stringSlice(info.Flags))
	}
	if len(info.ACLFlags) > 0 {
		fields = append(fields, "ACLFlags: "+stringSlice(info.ACLFlags))
	}
	if info.FirstKeyPos != 0 {
		fields = append(fields, fmt.Sprintf("FirstKeyPos: %d", info.FirstKeyPos))
	}
	if info.LastKeyPos != 0 {
		fields = append(fields, fmt.Sprintf("LastKeyPos: %d", info.LastKeyPos))
	}
	if info.StepCount != 0 {
		fields = append(fields, fmt.Sprintf("StepCount: %d", info.StepCount))
	}
	if info.ReadOnly {
		fields = append(fields, "ReadOnly: true")
	}
	if len(info.Tips) > 0 {
		fields = append(fields, "Tips: "+stringSlice(info.Tips))
	}
	if len(info.KeySpecs) > 0 {
		specs := make([]string, 0, len(info.KeySpecs))
		for _, ks := range info.KeySpecs {
			specs = append(specs, "{"+keySpec(ks)+"}")
		}
		fields = append(fields, "KeySpecs: []KeySpec{"+strings.Join(specs, ", ")+"}")
	}
	return strings.Join(fields, ", ")
}

func keySpec(ks redis.KeySpec) string {
	var fields []string
	if len(ks.Flags) > 0 {
		fields = append(fields, "Flags: "+stringSlice(ks.Flags))
	}
	if ks.BeginSearch != "" {
		fields = append(fields, fmt.Sprintf("BeginSearch: %q", ks.BeginSearch))
	}
	if ks.Index != 0 {
		fields = append(fields, fmt.Sprintf("Index: %d", ks.Index))
	}
	if ks.Keyword != "" {
		fields = append(fields, fmt.Sprintf("Keyword: %q", ks.Keyword))
	}
	if ks.StartFrom != 0 {
		fields = append(fields, fmt.Sprintf("StartFrom: %d", ks.StartFrom))
	}
	if ks.FindKeys != "" {
		fields = append(fields, fmt.Sprintf("FindKeys: %q", ks.FindKeys))
	}
	if ks.LastKey != 0 {
		fields = append(fields, fmt.Sprintf("LastKey: %d", ks.LastKey))
	}
	if ks.KeyStep != 0 {
		fields = append(fields, fmt.Sprintf("KeyStep: %d", ks.KeyStep))
	}
	if ks.Limit != 0 {
		fields = append(fields, fmt.Sprintf("Limit: %d", ks.Limit))
	}
	if ks.KeyNumIdx != 0 {
		fields = append(fields, fmt.Sprintf("KeyNumIdx: %d", ks.KeyNumIdx))
	}
	if ks.FirstKey != 0 {
		fields = append(fields, fmt.Sprintf("FirstKey: %d", ks.FirstKey))
	}
	return strings.Join(fields, ", ")
}

func stringSlice(vals []string) string {
	quoted := make([]string, len(vals))
	for i, v := range vals {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func describeServer(ctx context.Context, client *redis.Client) string {
	desc := "unknown"
	if info, err := client.Info(ctx, "server").Result(); err == nil {
		if m := regexp.MustCompile(`redis_version:(\S+)`).FindStringSubmatch(info); m != nil {
			desc = "redis_version " + m[1]
		}
	}
	var mods []string
	if reply, err := client.Do(ctx, "module", "list").Result(); err == nil {
		if items, ok := reply.([]interface{}); ok {
			for _, m := range items {
				fields, ok := m.(map[interface{}]interface{})
				if !ok {
					continue
				}
				name, _ := fields["name"].(string)
				if name != "" {
					mods = append(mods, fmt.Sprintf("%s %v", name, fields["ver"]))
				}
			}
		}
		sort.Strings(mods)
	}
	if len(mods) > 0 {
		desc += "; modules: " + strings.Join(mods, ", ")
	}
	// desc lands in a line comment of the generated file: a control character
	// (e.g. a newline in a module name) could otherwise terminate the comment
	// and inject source.
	return strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return -1
		}
		return r
	}, desc)
}
