name: 'Run go-redis tests'
description: 'Runs go-redis tests against different Redis versions and configurations'
inputs:
  go-version:
    description: 'Go version to use for running tests'
    default: '1.24'
  redis-version:
    description: 'Redis version to test against'
    required: true
  repository:
    description: 'Repository to checkout'
    required: false
  ref:
    description: 'Branch to checkout'
    required: false
  client-libs-test-image:
    description: 'Client libs test image tag'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - name: Set up ${{ inputs.go-version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}

    - name: Setup Test environment
      env:
        REDIS_VERSION: ${{ inputs.redis-version }}
        CLIENT_LIBS_TEST_IMAGE: ${{ inputs.client-libs-test-image }}
      run: |
        set -e

        if redis_version_np=$(echo "$REDIS_VERSION" | grep -oP '^\d+.\d+'); then
          echo "REDIS_VERSION=${redis_version_np}" >> "$GITHUB_ENV"
        else
          echo "REDIS_VERSION=${REDIS_VERSION}" >> "$GITHUB_ENV"
        fi

        if [[ -n "$CLIENT_LIBS_TEST_IMAGE" ]]; then
          echo "CLIENT_LIBS_TEST_IMAGE=${CLIENT_LIBS_TEST_IMAGE}" >> "$GITHUB_ENV"
        else
          # Mapping of redis version to redis testing containers
          declare -A redis_version_mapping=(
            ["8.6.x"]="custom-21860421418-debian-amd64"
            ["8.4.x"]="8.4.0"
            ["8.2.x"]="8.2.1-pre"
            ["8.0.x"]="8.0.2"
          )

          if [[ -v redis_version_mapping[$REDIS_VERSION] ]]; then
            echo "CLIENT_LIBS_TEST_IMAGE=redislabs/client-libs-test:${redis_version_mapping[$REDIS_VERSION]}" >> "$GITHUB_ENV"
          else
            echo "Version not found in the mapping and CLIENT_LIBS_TEST_IMAGE was not provided."
            exit 1
          fi
        fi
        sleep 10 # wait for redis to start
      shell: bash
    - name: Set up Docker Compose environment with redis ${{ inputs.redis-version }}
      run: |
        make docker.start
        sleep 5
      shell: bash
    - name: Run tests
      env:
        RCE_DOCKER: "true"
        RE_CLUSTER: "false"
      run: |
        make test.ci
      shell: bash