name: Go

on:
  push:
    branches: [master, v9, 'v9.*', 'RED-187316*']
  pull_request:
    branches: [master, v9, v9.7, v9.8, 'ndyakov/**', 'ofekshenawa/**', 'ce/**']

permissions:
  contents: read

jobs:
  test-redis-ce:
    name: test-redis-ce
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          redis-version:
            - "8.6.x" # Redis CE 8.6
          go-version:
            - "1.24.x"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          go-version: ${{matrix.go-version}}
          redis-version: ${{ matrix.redis-version }}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}

